# -*- coding: utf-8 -*-
"""mimiciii_sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PTd7Zdon-pVCmJWf6PHqEyb3HHduT9Zo

# AI in Healthcare - Assignment 2: MIMIC-III SQL

### Connect to MIMIC-III Through Google BigQuery
"""

# Auth is meant for Google Colab. May have to set up dataset locally or create your own Big Query dataset
# Standard Jupyter Notebook may have a different setup process
from google.colab import auth
from google.cloud import bigquery
bq_client = bigquery.Client(project = "your_project_id")
auth.authenticate_user()

## Import pandas
import pandas as pd

"""### Query 1 - Parkinson's by Gender"""

bq_client.query('''
SELECT gender, COUNT(*) AS num_patients
FROM `physionet-data.mimiciii_clinical.patients`
WHERE subject_id IN (
    SELECT subject_id FROM physionet-data.mimiciii_clinical.diagnoses_icd WHERE icd9_code = '3320'
)
GROUP BY gender;
''').to_dataframe()

"""### Query 2 - Parkinson's by Ethnicity"""

bq_client.query('''
WITH ethnicity_distribution AS (
    SELECT
        ethnicity,
        COUNT(DISTINCT subject_id) AS num_patients
    FROM physionet-data.mimiciii_clinical.admissions
    WHERE subject_id IN (
        SELECT DISTINCT subject_id
        FROM physionet-data.mimiciii_clinical.diagnoses_icd
        WHERE icd9_code = '3320'
    )
    GROUP BY ethnicity
),
total_ethnicity_admissions AS (
    SELECT
        ethnicity,
        COUNT(DISTINCT subject_id) AS total_admissions
    FROM physionet-data.mimiciii_clinical.admissions
    GROUP BY ethnicity
)
SELECT
    e.ethnicity,
    e.num_patients,
    t.total_admissions,
    (e.num_patients / t.total_admissions) AS percentage_for_ethnicity
FROM ethnicity_distribution e
JOIN total_ethnicity_admissions t ON e.ethnicity = t.ethnicity
ORDER BY percentage_for_ethnicity DESC;
''').to_dataframe()

"""### Query 3 - Patient's with Parkinson's Age Distribution at First Admission"""

bq_client.query('''
WITH first_admission AS (
    SELECT
        p.subject_id,
        DATE_DIFF(DATE(MIN(a.admittime)),
                  ARRAY_AGG(p.dob ORDER BY a.admittime LIMIT 1)[OFFSET(0)],
                  YEAR) AS age_at_first_admission
    FROM physionet-data.mimiciii_clinical.patients p
    JOIN physionet-data.mimiciii_clinical.admissions a
        ON p.subject_id = a.subject_id
    WHERE p.subject_id IN (
        SELECT subject_id FROM physionet-data.mimiciii_clinical.diagnoses_icd
        WHERE icd9_code = '3320'
    )
    GROUP BY p.subject_id -- Grouping by patient to ensure each one is counted once
    HAVING age_at_first_admission <= 110
)
SELECT
    MIN(age_at_first_admission) AS min_age,
    APPROX_QUANTILES(age_at_first_admission, 4)[OFFSET(1)] AS Q1,
    AVG(age_at_first_admission) AS avg_age,
    APPROX_QUANTILES(age_at_first_admission, 4)[OFFSET(3)] AS Q3,
    MAX(age_at_first_admission) AS max_age
FROM first_admission;
''').to_dataframe()

"""### Query 4 - Readmissions for Parkinson's Patients"""

bq_client.query('''
WITH admission_data AS (
    SELECT subject_id, COUNT(DISTINCT hadm_id) AS total_admissions
    FROM physionet-data.mimiciii_clinical.admissions
    WHERE subject_id IN (
        SELECT subject_id FROM physionet-data.mimiciii_clinical.diagnoses_icd
        WHERE icd9_code = '3320'
    )
    GROUP BY subject_id
)
SELECT
    COUNT(DISTINCT subject_id) AS total_patients,
    SUM(total_admissions) AS total_admissions,
    COUNT(CASE WHEN total_admissions > 1 THEN subject_id END) AS readmitted_patients,
    COUNT(CASE WHEN total_admissions >= 3 THEN subject_id END) AS patients_admitted_atleast_3_times
FROM admission_data;
''').to_dataframe()

"""### Query 5 - Parkinson's by Readmission Time"""

bq_client.query('''
WITH readmission_times AS (
    SELECT
        subject_id,
        TIMESTAMP_DIFF(
            LEAD(admittime) OVER(PARTITION BY subject_id ORDER BY admittime),
            dischtime,
            DAY
        ) AS days_before_readmission
    FROM physionet-data.mimiciii_clinical.admissions
    WHERE subject_id IN (
        SELECT subject_id FROM physionet-data.mimiciii_clinical.diagnoses_icd
        WHERE icd9_code = '3320'
    )
)
SELECT
    AVG(days_before_readmission) AS avg_days_before_readmission
FROM readmission_times
WHERE days_before_readmission IS NOT NULL;
''').to_dataframe()

"""### Query 6 - Parkinson's Patients vs. Other Patients Lenth of Stay"""

bq_client.query('''
SELECT
    CASE
        WHEN subject_id IN (
            SELECT subject_id FROM physionet-data.mimiciii_clinical.diagnoses_icd
            WHERE icd9_code = '3320'
        ) THEN 'Parkinsons Patients'
        ELSE 'Other Patients'
    END AS patient_group,
    AVG(TIMESTAMP_DIFF(dischtime, admittime, Day)) AS avg_length_of_stay_days
FROM physionet-data.mimiciii_clinical.admissions
GROUP BY patient_group;
''').to_dataframe()

"""### Query 7 - Top Co-occuring diagnoses with Parkinson's Patients"""

bq_client.query('''
SELECT
    d2.icd9_code,
    dicd.long_title,
    COUNT(DISTINCT d2.subject_id) AS co_occurrence_count
FROM physionet-data.mimiciii_clinical.diagnoses_icd d
JOIN physionet-data.mimiciii_clinical.diagnoses_icd d2
    ON d.subject_id = d2.subject_id
JOIN physionet-data.mimiciii_clinical.d_icd_diagnoses dicd
    ON d2.icd9_code = dicd.icd9_code
WHERE d.icd9_code = '3320' AND d2.icd9_code != '3320'
GROUP BY d2.icd9_code, dicd.long_title
ORDER BY co_occurrence_count DESC
LIMIT 10;
''').to_dataframe()

"""### Query 8 - Top Medications Administered to Parkinson's Patients"""

bq_client.query('''
SELECT
    pr.drug,
    COUNT(DISTINCT pr.subject_id) AS num_patients_prescribed
FROM physionet-data.mimiciii_clinical.prescriptions pr
JOIN physionet-data.mimiciii_clinical.diagnoses_icd d
    ON pr.subject_id = d.subject_id
WHERE d.icd9_code = '3320'
GROUP BY pr.drug
ORDER BY num_patients_prescribed DESC
LIMIT 10;
''').to_dataframe()

"""### Query 9 - Top Procedures Performed on Parkinson's Patients"""

bq_client.query('''
SELECT
    pr.icd9_code,
    dicd.long_title AS procedure_description,
    COUNT(DISTINCT pr.subject_id) AS num_patients
FROM
    `physionet-data.mimiciii_clinical.procedures_icd` pr
JOIN
    `physionet-data.mimiciii_clinical.diagnoses_icd` d
    ON pr.subject_id = d.subject_id
JOIN
    `physionet-data.mimiciii_clinical.d_icd_procedures` dicd
    ON pr.icd9_code = dicd.icd9_code
WHERE
    d.icd9_code = '3320'
GROUP BY
    pr.icd9_code, dicd.long_title
ORDER BY
    num_patients DESC
LIMIT 10;
''').to_dataframe()

"""### Query 10 - In-hospital Mortality Rate of Parkinson's Patients vs. Other Patients"""

bq_client.query('''
SELECT
    CASE
        WHEN subject_id IN (
            SELECT subject_id FROM physionet-data.mimiciii_clinical.diagnoses_icd
            WHERE icd9_code = '3320'
        ) THEN 'Parkinsons Patients'
        ELSE 'Other Patients'
    END AS patient_group,
    COUNT(DISTINCT subject_id) AS num_patients,  -- Count distinct subject_id to get unique patients
    SUM(CASE WHEN hospital_expire_flag = 1 THEN 1 ELSE 0 END) AS num_deaths,
    SUM(CASE WHEN hospital_expire_flag = 1 THEN 1 ELSE 0 END) / COUNT(DISTINCT subject_id) AS mortality_rate
FROM physionet-data.mimiciii_clinical.admissions
GROUP BY patient_group;
''').to_dataframe()